name: Demo GitHub Actions

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  matrix-performance:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 2

      matrix:
        node: [14, 16, 18, 20]

    steps:
      - run: echo "Testing Node ${{ matrix.node }}"
