name: Demo GitHub Actions

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  git-history:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git log --oneline
