name: Demo GitHub Actions

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  context-demo:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Usuario: ${{ github.actor }}"
      - run: |
          echo "Repo: ${{ github.repository }}"
      - run: |
          echo "Rama: ${{ github.ref }}"
      - run: |
          echo "Run number: ${{ github.run_number }}"
